// mapbox default styles: mapbox://styles/mapbox/streets-v11

import Head from 'next/head'
import mapboxgl from 'mapbox-gl'
import { useEffect } from 'react'

mapboxgl.accessToken =
    'pk.eyJ1IjoiZ2F1dGFtcGIiLCJhIjoiY2tzNGVzOHcxMWI2YjJ1cW12bjhmd3J6NiJ9._r1cFrkSyBDABOpDBwfIlg'

export default function Home() {
    useEffect(() => {
        const map = new mapboxgl.Map({
            container: 'map',
            style: 'mapbox://styles/gautampb/ckvmvkd9w287u14mwslt61b3e',
            center: [-99.29011, 39.39172],
            zoom: 3,
        })
    }, [])

    return (
        <div className="h-screen bg-blue-500 flex flex-col">
            <Head>
                <title>Uber Clone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="bg-red-500 flex-1" id="map">
                Map
            </div>

            <div className="bg-green-500 flex-1">Start</div>
        </div>
    )
}
