import Head from 'next/head'
import Map from './components/Map'
import Image from 'next/image'
import ActionButton from './components/ActionButton'

export default function Home() {
    return (
        <div className="h-screen flex flex-col">
            <Head>
                <title>Uber Clone</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Map />

            <div className="flex-1 p-5 space-y-5">
                {/* HEADER */}
                <div className="flex items-center justify-between">
                    <h1 className="font-semibold text-5xl">UBER</h1>

                    <div className="flex items-center space-x-4">
                        <h1 className="text-sm">Elon Musk</h1>
                        <div>
                            <Image
                                src="https://media.gq.com/photos/566ac3fec0f741b430e641e7/4:3/w_1480,h_1110,c_limit/elon-musk-gq-1215-01-sq.jpg"
                                alt=""
                                width={50}
                                height={50}
                                className="rounded-full"
                            />
                        </div>
                    </div>
                </div>

                {/* ACTION BUTTONS */}
                <div className="flex space-x-4">
                    <ActionButton
                        imageSrc="https://i.ibb.co/cyvcpfF/uberx.png"
                        title="Ride"
                        link="/search"
                    />

                    <ActionButton
                        imageSrc="https://i.ibb.co/n776JLm/bike.png"
                        title="2 Wheels"
                        link="/"
                    />

                    <ActionButton
                        imageSrc="https://i.ibb.co/5RjchBg/uberschedule.png"
                        title="Reserver"
                        link="/"
                    />
                </div>

                {/* INPUT BUTTONS */}
                <div className="h-20 bg-gray-200 text-2xl p-4 flex items-center mt-8">
                    <h1>Where to?</h1>
                </div>
            </div>
        </div>
    )
}
